FROM php:8.3-cli

WORKDIR /var/www/html

RUN install-php-extensions \
    pdo_mysql \
    opcache \
    zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --optimize-autoloader --no-interaction

RUN chown -R www-data:www-data storage bootstrap/cache

CMD php artisan serve --host=0.0.0.0 --port=${PORT:-10000}
